export const drains = [
  {
     id: "penrose",
    name: "درن پنرز (Penrose)",
    image: "/images/penrose.jpeg", 
    usage: "تخلیه ترشحات سطحی زخم و جلوگیری از تجمع ترشحات در ناحیه جراحی.",
    complications: "عفونت، خارج شدن ناخواسته، تحریک پوست.",
    care: "ضدعفونی مرتب محل خروج، بررسی میزان ترشح، فیکس‌کردن برای جلوگیری از خروج.",
  },
  {
     id: "Corrugated",
    name: "درن کاروگیت (Corrugated)",
    image: "/images/corrugated.png",
    usage: "تخلیه ترشحات از زخم‌های عمیق‌تر یا نواحی جراحی بزرگ.",
    complications: "عفونت، تحریک پوست، درد در محل.",
    care: "بررسی روزانه میزان ترشح، جلوگیری از بسته شدن مسیر خروجی.",
  },
  {
     id: "Hemovac",
    name: "درن هموواک (Hemovac)",
    image: "/images/hemovac.jpg",
    usage: "برای جراحی‌های ارتوپدی و شکمی جهت تخلیه خون یا سرم.",
    complications: "انسداد، عفونت، کاهش فشار منفی.",
    care: "اطمینان از فشار منفی کافی، تخلیه منظم، بررسی محل درن.",
  },
  {
     id: "Jackson-Pratt",
    name: "درن جکسون-پرات (Jackson-Pratt)",
    image: "/images/jackson-pratt.webp",
    usage: "در جراحی‌های شکمی، پستان، تیروئید برای تخلیه مایعات.",
    complications: "لخته شدن، عفونت، کشیده شدن ناگهانی.",
    care: "تخلیه روزانه، ثبت حجم و رنگ ترشح، شستشو در صورت نیاز.",
  },
  {
     id: "External Ventricular Drain",
    name: "درن EVD (External Ventricular Drain)",
    image: "/images/External Ventricular Drain.jpg",
    usage: "تخلیه مایع مغزی-نخاعی در بیماران با فشار داخل جمجمه بالا.",
    complications: "عفونت مغزی، خونریزی، انسداد مسیر درن.",
    care: "استریل کامل، بررسی فشار و سطح چشمی، ثبت دقیق حجم خروجی.",
  },
  {
     id: "Chest Tube",
    name: "چست تیوب (Chest Tube)",
    image: "/images/Chest Tube.png",
    usage: "تخلیه هوا، خون یا مایع از فضای پلور.",
    complications: "پنوموتوراکس مجدد، درد، عفونت، جابجایی لوله.",
    care: "بررسی حرکت آب در چمبر، بررسی محل، گزارش نشت هوا.",
  },
  {
     id: "Pigtail",
    name: "درن پیگ‌تیل (Pigtail)",
    image: "/images/pigtail.jpg",
    usage: "تخلیه آبسه، پلورال افیوژن، کیست‌ها با کمترین تهاجم.",
    complications: "بسته شدن مسیر، درد، عفونت.",
    care: "بررسی روزانه حجم و وضعیت ترشح، فیکس کردن لوله.",
  },
];
