export const rhythms = [
  // Normal Rhythms
  {
    id: "sinus",
    name: "ریتم سینوسی",
    type: "نرمال",
    description: "ریتم طبیعی با موج P و فاصله PR نرمال.",
    bpmRange: "60-100",
    image: "/images/sinus.png.jpg",
  },
  {
    id: "sinus-bradycardia",
    name: "سینوس برادیکاردی",
    type: "نرمال",
    description: "ضربان کمتر از 60 در دقیقه.",
    bpmRange: "<60",
    image: "/images/sinus-bradycardia.png.jpg",
  },
  {
    id: "sinus-tachycardia",
    name: "سینوس تاکی‌کاردی",
    type: "نرمال",
    description: "ضربان بیش از 100 در دقیقه.",
    bpmRange: ">100",
    image: "/images/sinus-tachycardia.png.jpg",
  },
  {
    id: "sinus-arrhythmia",
    name: "سینوس آریتمی",
    type: "نرمال",
    description: "تغییر طبیعی فاصله R-R، معمولاً در کودکان.",
    bpmRange: "متغیر",
    image: "/images/sinus-arrhythmia.png",
  },

  // Atrial
  {
    id: "afib",
    name: "فیبریلاسیون دهلیزی",
    type: "دهلیزی",
    description: "ریتم نامنظم با غیبت موج P مشخص.",
    bpmRange: "متغیر",
    image: "/images/afib.png",
  },
  {
    id: "aflutter",
    name: "فلوتر دهلیزی",
    type: "دهلیزی",
    description: "موج‌های f شبیه اره، ریتم منظم.",
    bpmRange: "250-350",
    image: "/images/aflutter.png",
  },
  {
    id: "pac",
    name: "ضربه زودرس دهلیزی (PAC)",
    type: "دهلیزی",
    description: "موج P زودرس با QRS طبیعی.",
    bpmRange: "نرمال + PVC",
    image: "/images/pac.png",
  },

  // Junctional
  {
    id: "junctional",
    name: "ریتم جانکشنال",
    type: "گره AV",
    description: "موج P غایب یا معکوس، QRS باریک.",
    bpmRange: "40-60",
    image: "/images/junctional.png",
  },
  {
    id: "accelerated-junctional",
    name: "جانکشنال سریع",
    type: "گره AV",
    description: "سرعت بیشتر از ریتم پایه جانکشنال.",
    bpmRange: "60-100",
    image: "/images/accelerated-junctional.png",
  },
  {
    id: "junctional-tachycardia",
    name: "تاکی‌کاردی جانکشنال",
    type: "گره AV",
    description: "ضربان بیش از 100، منشأ گره AV.",
    bpmRange: ">100",
    image: "/images/junctional-tachycardia.png",
  },

  // Ventricular
  {
    id: "pvc",
    name: "ضربه زودرس بطنی (PVC)",
    type: "بطنی",
    description: "QRS پهن و زودرس، بدون موج P.",
    bpmRange: "نرمال + PVC",
    image: "/images/pvc.png",
  },
  {
    id: "vtach",
    name: "تاکی‌کاردی بطنی (VT)",
    type: "بطنی",
    description: "سه یا بیشتر PVC متوالی، خطرناک.",
    bpmRange: ">100",
    image: "/images/vtach.png",
  },
  {
    id: "vfib",
    name: "فیبریلاسیون بطنی",
    type: "بطنی",
    description: "فعالیت الکتریکی کاملاً بی‌نظم، تهدید حیات.",
    bpmRange: "غیرقابل اندازه‌گیری",
    image: "/images/vfib.png",
  },
  {
    id: "asystole",
    name: "اسیستول (خط صاف)",
    type: "ایست قلبی",
    description: "هیچ فعالیت الکتریکی، خط صاف.",
    bpmRange: "0",
    image: "/images/asystole.png",
  },

  // Blocks
  {
    id: "av-block-1",
    name: "بلوک درجه ۱ AV",
    type: "بلوک",
    description: "فاصله PR طولانی‌تر از 0.2 ثانیه.",
    bpmRange: "نرمال",
    image: "/images/av-block-1.png",
  },
  {
    id: "av-block-2-type1",
    name: "بلوک درجه ۲ نوع ۱ (ونکباخ)",
    type: "بلوک",
    description: "طولانی‌شدن PR تا افت QRS.",
    bpmRange: "متغیر",
    image: "/images/av-block-2-1.png",
  },
  {
    id: "av-block-2-type2",
    name: "بلوک درجه ۲ نوع ۲",
    type: "بلوک",
    description: "افت ناگهانی QRS بدون طولانی شدن PR.",
    bpmRange: "کم",
    image: "/images/av-block-2-2.png",
  },
  {
    id: "av-block-3",
    name: "بلوک کامل (درجه ۳)",
    type: "بلوک",
    description: "عدم ارتباط دهلیز و بطن.",
    bpmRange: "کم",
    image: "/images/av-block-3.png",
  },
];
